# Generated by Django 4.0.4 on 2022-10-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='car_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
