# Generated by Django 4.0.4 on 2022-06-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_team_created_date_alter_team_google_plus_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topbar_phone', models.CharField(max_length=255)),
                ('topbar_email', models.EmailField(max_length=255)),
                ('open_hours', models.CharField(max_length=255)),
            ],
        ),
    ]
