# Generated by Django 4.0.4 on 2022-07-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_description_alter_car_doors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='main_photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo_1',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo_2',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo_3',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo_4',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
