# Generated by Django 4.0.4 on 2022-07-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_photo_5_car_photo_6_car_photo_7_car_photo_8_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo_5',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
