# Generated by Django 4.0.4 on 2022-07-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_photo_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo_6',
            field=models.ImageField(default='media/photos/default.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo_7',
            field=models.ImageField(default='media/photos/default.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo_8',
            field=models.ImageField(default='media/photos/default.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo_9',
            field=models.ImageField(default='media/photos/default.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
