# Generated by Django 4.0.4 on 2022-07-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_photo_6_alter_car_photo_7_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo_6',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo_7',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo_8',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo_9',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
